/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module tt_um_zedulo_spitest1(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire \spidevice.arm_tx ;
  wire \spidevice.data_ready ;
  wire \spidevice.debug ;
  wire \spidevice.led_reset ;
  wire \spidevice.led_status ;
  wire \spidevice.main_reg[0] ;
  wire \spidevice.main_reg[1] ;
  wire \spidevice.main_reg[2] ;
  wire \spidevice.main_reg[3] ;
  wire \spidevice.main_reg[4] ;
  wire \spidevice.main_reg[5] ;
  wire \spidevice.main_reg[6] ;
  wire \spidevice.main_reg[7] ;
  wire \spidevice.prev_spi_clk ;
  wire \spidevice.spi_clk_buff[0][0] ;
  wire \spidevice.spi_clk_buff[1][0] ;
  wire \spidevice.spi_completed ;
  wire \spidevice.spi_count[0] ;
  wire \spidevice.spi_count[1] ;
  wire \spidevice.spi_count[2] ;
  wire \spidevice.spi_miso ;
  wire \spidevice.storage[0] ;
  wire \spidevice.storage[1] ;
  wire \spidevice.storage[2] ;
  wire \spidevice.storage[3] ;
  wire \spidevice.storage[4] ;
  wire \spidevice.storage[5] ;
  wire \spidevice.storage[6] ;
  wire \spidevice.storage[7] ;
  wire \spidevice.target ;
  sg13g2_inv_1 _152_ (
    .A(ui_in[2]),
    .Y(_090_)
  );
  sg13g2_inv_1 _153_ (
    .A(\spidevice.main_reg[6] ),
    .Y(_091_)
  );
  sg13g2_inv_1 _154_ (
    .A(\spidevice.main_reg[4] ),
    .Y(_092_)
  );
  sg13g2_inv_1 _155_ (
    .A(\spidevice.main_reg[1] ),
    .Y(_093_)
  );
  sg13g2_inv_1 _156_ (
    .A(\spidevice.main_reg[0] ),
    .Y(_094_)
  );
  sg13g2_inv_1 _157_ (
    .A(\spidevice.data_ready ),
    .Y(_095_)
  );
  sg13g2_inv_1 _158_ (
    .A(\spidevice.prev_spi_clk ),
    .Y(_096_)
  );
  sg13g2_inv_1 _159_ (
    .A(rst_n),
    .Y(_097_)
  );
  sg13g2_or3_1 _160_ (
    .A(ui_in[2]),
    .B(\spidevice.spi_completed ),
    .C(\spidevice.arm_tx ),
    .X(_098_)
  );
  sg13g2_nand3b_1 _161_ (
    .A_N(\spidevice.prev_spi_clk ),
    .B(\spidevice.spi_clk_buff[0][0] ),
    .C(\spidevice.spi_clk_buff[1][0] ),
    .Y(_099_)
  );
  sg13g2_inv_1 _162_ (
    .A(_099_),
    .Y(_100_)
  );
  sg13g2_or2_1 _163_ (
    .A(_098_),
    .B(_099_),
    .X(_101_)
  );
  sg13g2_and3_1 _164_ (
    .A(\spidevice.spi_count[0] ),
    .B(\spidevice.spi_count[1] ),
    .C(\spidevice.spi_count[2] ),
    .X(_102_)
  );
  sg13g2_nand2_1 _165_ (
    .A(ui_in[2]),
    .B(rst_n),
    .Y(_103_)
  );
  sg13g2_nand2b_1 _166_ (
    .A_N(ui_in[2]),
    .B(\spidevice.data_ready ),
    .Y(_104_)
  );
  sg13g2_nand2_1 _167_ (
    .A(rst_n),
    .B(_104_),
    .Y(_105_)
  );
  sg13g2_nand3_1 _168_ (
    .A(rst_n),
    .B(_102_),
    .C(_104_),
    .Y(_106_)
  );
  sg13g2_nand2_1 _169_ (
    .A(\spidevice.spi_completed ),
    .B(_105_),
    .Y(_107_)
  );
  sg13g2_o21ai_1 _170_ (
    .A1(_101_),
    .A2(_106_),
    .B1(_107_),
    .Y(_000_)
  );
  sg13g2_nor3_1 _171_ (
    .A(\spidevice.spi_clk_buff[1][0] ),
    .B(\spidevice.spi_clk_buff[0][0] ),
    .C(_096_),
    .Y(_108_)
  );
  sg13g2_nor4_1 _172_ (
    .A(ui_in[2]),
    .B(\spidevice.spi_completed ),
    .C(\spidevice.data_ready ),
    .D(_097_),
    .Y(_109_)
  );
  sg13g2_o21ai_1 _173_ (
    .A1(\spidevice.arm_tx ),
    .A2(_108_),
    .B1(_109_),
    .Y(_110_)
  );
  sg13g2_mux2_1 _174_ (
    .A0(\spidevice.main_reg[7] ),
    .A1(\spidevice.spi_miso ),
    .S(_110_),
    .X(_001_)
  );
  sg13g2_a22oi_1 _175_ (
    .A1(_095_),
    .A2(_099_),
    .B1(_104_),
    .B2(_098_),
    .Y(_111_)
  );
  sg13g2_inv_1 _176_ (
    .A(_111_),
    .Y(_112_)
  );
  sg13g2_a22oi_1 _177_ (
    .A1(_090_),
    .A2(\spidevice.data_ready ),
    .B1(_102_),
    .B2(_111_),
    .Y(_113_)
  );
  sg13g2_nor2_1 _178_ (
    .A(\spidevice.main_reg[5] ),
    .B(\spidevice.main_reg[4] ),
    .Y(_114_)
  );
  sg13g2_nor2_1 _179_ (
    .A(\spidevice.main_reg[7] ),
    .B(\spidevice.main_reg[6] ),
    .Y(_115_)
  );
  sg13g2_and2_1 _180_ (
    .A(\spidevice.main_reg[5] ),
    .B(\spidevice.main_reg[4] ),
    .X(_116_)
  );
  sg13g2_nor4_1 _181_ (
    .A(\spidevice.main_reg[7] ),
    .B(\spidevice.main_reg[6] ),
    .C(_114_),
    .D(_116_),
    .Y(_117_)
  );
  sg13g2_nor2_1 _182_ (
    .A(_095_),
    .B(_117_),
    .Y(_118_)
  );
  sg13g2_o21ai_1 _183_ (
    .A1(_113_),
    .A2(_118_),
    .B1(\spidevice.led_status ),
    .Y(_119_)
  );
  sg13g2_nand4_1 _184_ (
    .A(\spidevice.main_reg[5] ),
    .B(_092_),
    .C(\spidevice.data_ready ),
    .D(_115_),
    .Y(_120_)
  );
  sg13g2_or3_1 _185_ (
    .A(_113_),
    .B(_118_),
    .C(_120_),
    .X(_121_)
  );
  sg13g2_nand3_1 _186_ (
    .A(rst_n),
    .B(_119_),
    .C(_121_),
    .Y(_002_)
  );
  sg13g2_a21o_1 _187_ (
    .A1(ui_in[2]),
    .A2(\spidevice.led_reset ),
    .B1(_097_),
    .X(_003_)
  );
  sg13g2_a21oi_1 _188_ (
    .A1(_102_),
    .A2(_111_),
    .B1(\spidevice.debug ),
    .Y(_030_)
  );
  sg13g2_nor2_1 _189_ (
    .A(_105_),
    .B(_030_),
    .Y(_004_)
  );
  sg13g2_nor2b_1 _190_ (
    .A(ui_in[2]),
    .B_N(\spidevice.spi_completed ),
    .Y(_031_)
  );
  sg13g2_a21oi_1 _191_ (
    .A1(rst_n),
    .A2(_031_),
    .B1(\spidevice.data_ready ),
    .Y(_032_)
  );
  sg13g2_nand2b_1 _192_ (
    .A_N(\spidevice.spi_completed ),
    .B(rst_n),
    .Y(_033_)
  );
  sg13g2_a21oi_1 _193_ (
    .A1(\spidevice.data_ready ),
    .A2(rst_n),
    .B1(_032_),
    .Y(_005_)
  );
  sg13g2_o21ai_1 _194_ (
    .A1(_097_),
    .A2(_031_),
    .B1(\spidevice.arm_tx ),
    .Y(_034_)
  );
  sg13g2_o21ai_1 _195_ (
    .A1(ui_in[2]),
    .A2(\spidevice.data_ready ),
    .B1(rst_n),
    .Y(_035_)
  );
  sg13g2_nand2_1 _196_ (
    .A(_034_),
    .B(_035_),
    .Y(_006_)
  );
  sg13g2_or2_1 _197_ (
    .A(\spidevice.data_ready ),
    .B(\spidevice.arm_tx ),
    .X(_036_)
  );
  sg13g2_a22oi_1 _198_ (
    .A1(_103_),
    .A2(_033_),
    .B1(_036_),
    .B2(_090_),
    .Y(_037_)
  );
  sg13g2_o21ai_1 _199_ (
    .A1(ui_in[2]),
    .A2(_100_),
    .B1(_037_),
    .Y(_038_)
  );
  sg13g2_and2_1 _200_ (
    .A(_108_),
    .B(_037_),
    .X(_039_)
  );
  sg13g2_o21ai_1 _201_ (
    .A1(_096_),
    .A2(_039_),
    .B1(_038_),
    .Y(_007_)
  );
  sg13g2_nor2_1 _202_ (
    .A(\spidevice.main_reg[7] ),
    .B(\spidevice.main_reg[5] ),
    .Y(_040_)
  );
  sg13g2_nand2_1 _203_ (
    .A(\spidevice.main_reg[6] ),
    .B(_040_),
    .Y(_041_)
  );
  sg13g2_nand3_1 _204_ (
    .A(\spidevice.main_reg[6] ),
    .B(\spidevice.main_reg[4] ),
    .C(_040_),
    .Y(_042_)
  );
  sg13g2_nor2b_1 _205_ (
    .A(\spidevice.target ),
    .B_N(\spidevice.storage[0] ),
    .Y(_043_)
  );
  sg13g2_a21oi_1 _206_ (
    .A1(\spidevice.target ),
    .A2(\spidevice.storage[4] ),
    .B1(_043_),
    .Y(_044_)
  );
  sg13g2_nand2b_1 _207_ (
    .A_N(_042_),
    .B(_044_),
    .Y(_045_)
  );
  sg13g2_a21oi_1 _208_ (
    .A1(_114_),
    .A2(_115_),
    .B1(_095_),
    .Y(_046_)
  );
  sg13g2_nor2_1 _209_ (
    .A(\spidevice.main_reg[0] ),
    .B(_111_),
    .Y(_047_)
  );
  sg13g2_a221oi_1 _210_ (
    .A1(_095_),
    .A2(ui_in[0]),
    .B1(_045_),
    .B2(_046_),
    .C1(_112_),
    .Y(_048_)
  );
  sg13g2_o21ai_1 _211_ (
    .A1(_047_),
    .A2(_048_),
    .B1(rst_n),
    .Y(_008_)
  );
  sg13g2_nor2b_1 _212_ (
    .A(\spidevice.target ),
    .B_N(\spidevice.storage[1] ),
    .Y(_049_)
  );
  sg13g2_a21oi_1 _213_ (
    .A1(\spidevice.target ),
    .A2(\spidevice.storage[5] ),
    .B1(_049_),
    .Y(_050_)
  );
  sg13g2_a21oi_1 _214_ (
    .A1(\spidevice.main_reg[6] ),
    .A2(\spidevice.main_reg[5] ),
    .B1(\spidevice.main_reg[7] ),
    .Y(_051_)
  );
  sg13g2_and2_1 _215_ (
    .A(\spidevice.data_ready ),
    .B(_051_),
    .X(_052_)
  );
  sg13g2_o21ai_1 _216_ (
    .A1(_042_),
    .A2(_050_),
    .B1(_051_),
    .Y(_053_)
  );
  sg13g2_o21ai_1 _217_ (
    .A1(_094_),
    .A2(\spidevice.data_ready ),
    .B1(_111_),
    .Y(_054_)
  );
  sg13g2_a21oi_1 _218_ (
    .A1(\spidevice.data_ready ),
    .A2(_053_),
    .B1(_054_),
    .Y(_055_)
  );
  sg13g2_o21ai_1 _219_ (
    .A1(\spidevice.main_reg[1] ),
    .A2(_111_),
    .B1(rst_n),
    .Y(_056_)
  );
  sg13g2_nor2_1 _220_ (
    .A(_055_),
    .B(_056_),
    .Y(_009_)
  );
  sg13g2_nor2b_1 _221_ (
    .A(\spidevice.target ),
    .B_N(\spidevice.storage[2] ),
    .Y(_057_)
  );
  sg13g2_a21oi_1 _222_ (
    .A1(\spidevice.target ),
    .A2(\spidevice.storage[6] ),
    .B1(_057_),
    .Y(_058_)
  );
  sg13g2_o21ai_1 _223_ (
    .A1(_042_),
    .A2(_058_),
    .B1(_051_),
    .Y(_059_)
  );
  sg13g2_o21ai_1 _224_ (
    .A1(_093_),
    .A2(\spidevice.data_ready ),
    .B1(_111_),
    .Y(_060_)
  );
  sg13g2_a21oi_1 _225_ (
    .A1(\spidevice.data_ready ),
    .A2(_059_),
    .B1(_060_),
    .Y(_061_)
  );
  sg13g2_o21ai_1 _226_ (
    .A1(\spidevice.main_reg[2] ),
    .A2(_111_),
    .B1(rst_n),
    .Y(_062_)
  );
  sg13g2_nor2_1 _227_ (
    .A(_061_),
    .B(_062_),
    .Y(_010_)
  );
  sg13g2_nor2b_1 _228_ (
    .A(\spidevice.target ),
    .B_N(\spidevice.storage[3] ),
    .Y(_063_)
  );
  sg13g2_a21oi_1 _229_ (
    .A1(\spidevice.target ),
    .A2(\spidevice.storage[7] ),
    .B1(_063_),
    .Y(_064_)
  );
  sg13g2_o21ai_1 _230_ (
    .A1(_042_),
    .A2(_064_),
    .B1(_052_),
    .Y(_065_)
  );
  sg13g2_o21ai_1 _231_ (
    .A1(\spidevice.main_reg[2] ),
    .A2(\spidevice.data_ready ),
    .B1(_111_),
    .Y(_066_)
  );
  sg13g2_nand2b_1 _232_ (
    .A_N(_066_),
    .B(_065_),
    .Y(_067_)
  );
  sg13g2_nand2_1 _233_ (
    .A(\spidevice.main_reg[3] ),
    .B(_112_),
    .Y(_068_)
  );
  sg13g2_nand3_1 _234_ (
    .A(rst_n),
    .B(_067_),
    .C(_068_),
    .Y(_011_)
  );
  sg13g2_nor2_1 _235_ (
    .A(\spidevice.data_ready ),
    .B(_101_),
    .Y(_069_)
  );
  sg13g2_a21oi_1 _236_ (
    .A1(\spidevice.main_reg[3] ),
    .A2(_069_),
    .B1(_097_),
    .Y(_070_)
  );
  sg13g2_o21ai_1 _237_ (
    .A1(_092_),
    .A2(_069_),
    .B1(_070_),
    .Y(_012_)
  );
  sg13g2_o21ai_1 _238_ (
    .A1(\spidevice.main_reg[5] ),
    .A2(_069_),
    .B1(rst_n),
    .Y(_071_)
  );
  sg13g2_a21oi_1 _239_ (
    .A1(_092_),
    .A2(_069_),
    .B1(_071_),
    .Y(_013_)
  );
  sg13g2_a21oi_1 _240_ (
    .A1(\spidevice.main_reg[5] ),
    .A2(_069_),
    .B1(_097_),
    .Y(_072_)
  );
  sg13g2_o21ai_1 _241_ (
    .A1(_091_),
    .A2(_069_),
    .B1(_072_),
    .Y(_014_)
  );
  sg13g2_o21ai_1 _242_ (
    .A1(\spidevice.main_reg[7] ),
    .A2(_069_),
    .B1(rst_n),
    .Y(_073_)
  );
  sg13g2_a21oi_1 _243_ (
    .A1(_091_),
    .A2(_069_),
    .B1(_073_),
    .Y(_015_)
  );
  sg13g2_nand3_1 _244_ (
    .A(_090_),
    .B(_100_),
    .C(_037_),
    .Y(_074_)
  );
  sg13g2_nand2_1 _245_ (
    .A(\spidevice.spi_count[0] ),
    .B(_038_),
    .Y(_075_)
  );
  sg13g2_o21ai_1 _246_ (
    .A1(\spidevice.spi_count[0] ),
    .A2(_074_),
    .B1(_075_),
    .Y(_016_)
  );
  sg13g2_nand2_1 _247_ (
    .A(\spidevice.spi_count[1] ),
    .B(_038_),
    .Y(_076_)
  );
  sg13g2_xnor2_1 _248_ (
    .A(\spidevice.spi_count[0] ),
    .B(\spidevice.spi_count[1] ),
    .Y(_077_)
  );
  sg13g2_o21ai_1 _249_ (
    .A1(_074_),
    .A2(_077_),
    .B1(_076_),
    .Y(_017_)
  );
  sg13g2_a21oi_1 _250_ (
    .A1(\spidevice.spi_count[0] ),
    .A2(\spidevice.spi_count[1] ),
    .B1(\spidevice.spi_count[2] ),
    .Y(_078_)
  );
  sg13g2_nor3_1 _251_ (
    .A(_102_),
    .B(_074_),
    .C(_078_),
    .Y(_079_)
  );
  sg13g2_a21o_1 _252_ (
    .A1(\spidevice.spi_count[2] ),
    .A2(_038_),
    .B1(_079_),
    .X(_018_)
  );
  sg13g2_nor2_1 _253_ (
    .A(_097_),
    .B(_104_),
    .Y(_080_)
  );
  sg13g2_inv_1 _254_ (
    .A(_080_),
    .Y(_081_)
  );
  sg13g2_nand3_1 _255_ (
    .A(_115_),
    .B(_116_),
    .C(_080_),
    .Y(_082_)
  );
  sg13g2_nand2_1 _256_ (
    .A(\spidevice.target ),
    .B(_082_),
    .Y(_083_)
  );
  sg13g2_o21ai_1 _257_ (
    .A1(_094_),
    .A2(_082_),
    .B1(_083_),
    .Y(_019_)
  );
  sg13g2_nor2_1 _258_ (
    .A(\spidevice.main_reg[4] ),
    .B(_041_),
    .Y(_084_)
  );
  sg13g2_nand3_1 _259_ (
    .A(\spidevice.target ),
    .B(_080_),
    .C(_084_),
    .Y(_085_)
  );
  sg13g2_mux2_1 _260_ (
    .A0(\spidevice.main_reg[0] ),
    .A1(\spidevice.storage[4] ),
    .S(_085_),
    .X(_020_)
  );
  sg13g2_mux2_1 _261_ (
    .A0(\spidevice.main_reg[1] ),
    .A1(\spidevice.storage[5] ),
    .S(_085_),
    .X(_021_)
  );
  sg13g2_mux2_1 _262_ (
    .A0(\spidevice.main_reg[2] ),
    .A1(\spidevice.storage[6] ),
    .S(_085_),
    .X(_022_)
  );
  sg13g2_mux2_1 _263_ (
    .A0(\spidevice.main_reg[3] ),
    .A1(\spidevice.storage[7] ),
    .S(_085_),
    .X(_023_)
  );
  sg13g2_nor4_1 _264_ (
    .A(\spidevice.main_reg[4] ),
    .B(\spidevice.target ),
    .C(_041_),
    .D(_081_),
    .Y(_086_)
  );
  sg13g2_mux2_1 _265_ (
    .A0(\spidevice.storage[0] ),
    .A1(\spidevice.main_reg[0] ),
    .S(_086_),
    .X(_024_)
  );
  sg13g2_mux2_1 _266_ (
    .A0(\spidevice.storage[1] ),
    .A1(\spidevice.main_reg[1] ),
    .S(_086_),
    .X(_025_)
  );
  sg13g2_mux2_1 _267_ (
    .A0(\spidevice.storage[2] ),
    .A1(\spidevice.main_reg[2] ),
    .S(_086_),
    .X(_026_)
  );
  sg13g2_mux2_1 _268_ (
    .A0(\spidevice.storage[3] ),
    .A1(\spidevice.main_reg[3] ),
    .S(_086_),
    .X(_027_)
  );
  sg13g2_mux2_1 _269_ (
    .A0(\spidevice.spi_clk_buff[0][0] ),
    .A1(ui_in[1]),
    .S(rst_n),
    .X(_028_)
  );
  sg13g2_nand2_1 _270_ (
    .A(\spidevice.spi_clk_buff[1][0] ),
    .B(_097_),
    .Y(_087_)
  );
  sg13g2_o21ai_1 _271_ (
    .A1(ui_in[2]),
    .A2(\spidevice.spi_clk_buff[0][0] ),
    .B1(rst_n),
    .Y(_088_)
  );
  sg13g2_nor2_1 _272_ (
    .A(ui_in[1]),
    .B(_103_),
    .Y(_089_)
  );
  sg13g2_a21oi_1 _273_ (
    .A1(_087_),
    .A2(_088_),
    .B1(_089_),
    .Y(_029_)
  );
  sg13g2_dfrbpq_1 _274_ (
    .CLK(clk),
    .D(_000_),
    .Q(\spidevice.spi_completed ),
    .RESET_B(_134_)
  );
  sg13g2_dfrbpq_1 _275_ (
    .CLK(clk),
    .D(_001_),
    .Q(\spidevice.spi_miso ),
    .RESET_B(_144_)
  );
  sg13g2_dfrbpq_1 _276_ (
    .CLK(clk),
    .D(_002_),
    .Q(\spidevice.led_status ),
    .RESET_B(_143_)
  );
  sg13g2_dfrbpq_1 _277_ (
    .CLK(clk),
    .D(_003_),
    .Q(\spidevice.led_reset ),
    .RESET_B(_141_)
  );
  sg13g2_dfrbpq_1 _278_ (
    .CLK(clk),
    .D(_004_),
    .Q(\spidevice.debug ),
    .RESET_B(_139_)
  );
  sg13g2_dfrbpq_1 _279_ (
    .CLK(clk),
    .D(_005_),
    .Q(\spidevice.data_ready ),
    .RESET_B(_137_)
  );
  sg13g2_dfrbpq_1 _280_ (
    .CLK(clk),
    .D(_006_),
    .Q(\spidevice.arm_tx ),
    .RESET_B(_135_)
  );
  sg13g2_dfrbpq_1 _281_ (
    .CLK(clk),
    .D(_007_),
    .Q(\spidevice.prev_spi_clk ),
    .RESET_B(_133_)
  );
  sg13g2_dfrbpq_1 _282_ (
    .CLK(clk),
    .D(_008_),
    .Q(\spidevice.main_reg[0] ),
    .RESET_B(_131_)
  );
  sg13g2_dfrbpq_1 _283_ (
    .CLK(clk),
    .D(_009_),
    .Q(\spidevice.main_reg[1] ),
    .RESET_B(_129_)
  );
  sg13g2_dfrbpq_1 _284_ (
    .CLK(clk),
    .D(_010_),
    .Q(\spidevice.main_reg[2] ),
    .RESET_B(_127_)
  );
  sg13g2_dfrbpq_1 _285_ (
    .CLK(clk),
    .D(_011_),
    .Q(\spidevice.main_reg[3] ),
    .RESET_B(_125_)
  );
  sg13g2_dfrbpq_1 _286_ (
    .CLK(clk),
    .D(_012_),
    .Q(\spidevice.main_reg[4] ),
    .RESET_B(_123_)
  );
  sg13g2_dfrbpq_1 _287_ (
    .CLK(clk),
    .D(_013_),
    .Q(\spidevice.main_reg[5] ),
    .RESET_B(_151_)
  );
  sg13g2_dfrbpq_1 _288_ (
    .CLK(clk),
    .D(_014_),
    .Q(\spidevice.main_reg[6] ),
    .RESET_B(_149_)
  );
  sg13g2_dfrbpq_1 _289_ (
    .CLK(clk),
    .D(_015_),
    .Q(\spidevice.main_reg[7] ),
    .RESET_B(_147_)
  );
  sg13g2_dfrbpq_1 _290_ (
    .CLK(clk),
    .D(_016_),
    .Q(\spidevice.spi_count[0] ),
    .RESET_B(_145_)
  );
  sg13g2_dfrbpq_1 _291_ (
    .CLK(clk),
    .D(_017_),
    .Q(\spidevice.spi_count[1] ),
    .RESET_B(_140_)
  );
  sg13g2_dfrbpq_1 _292_ (
    .CLK(clk),
    .D(_018_),
    .Q(\spidevice.spi_count[2] ),
    .RESET_B(_136_)
  );
  sg13g2_dfrbpq_1 _293_ (
    .CLK(clk),
    .D(_019_),
    .Q(\spidevice.target ),
    .RESET_B(_132_)
  );
  sg13g2_dfrbpq_1 _294_ (
    .CLK(clk),
    .D(_020_),
    .Q(\spidevice.storage[4] ),
    .RESET_B(_130_)
  );
  sg13g2_dfrbpq_1 _295_ (
    .CLK(clk),
    .D(_021_),
    .Q(\spidevice.storage[5] ),
    .RESET_B(_128_)
  );
  sg13g2_dfrbpq_1 _296_ (
    .CLK(clk),
    .D(_022_),
    .Q(\spidevice.storage[6] ),
    .RESET_B(_126_)
  );
  sg13g2_dfrbpq_1 _297_ (
    .CLK(clk),
    .D(_023_),
    .Q(\spidevice.storage[7] ),
    .RESET_B(_124_)
  );
  sg13g2_dfrbpq_1 _298_ (
    .CLK(clk),
    .D(_024_),
    .Q(\spidevice.storage[0] ),
    .RESET_B(_122_)
  );
  sg13g2_dfrbpq_1 _299_ (
    .CLK(clk),
    .D(_025_),
    .Q(\spidevice.storage[1] ),
    .RESET_B(_150_)
  );
  sg13g2_dfrbpq_1 _300_ (
    .CLK(clk),
    .D(_026_),
    .Q(\spidevice.storage[2] ),
    .RESET_B(_148_)
  );
  sg13g2_dfrbpq_1 _301_ (
    .CLK(clk),
    .D(_027_),
    .Q(\spidevice.storage[3] ),
    .RESET_B(_146_)
  );
  sg13g2_dfrbpq_1 _302_ (
    .CLK(clk),
    .D(_028_),
    .Q(\spidevice.spi_clk_buff[0][0] ),
    .RESET_B(_142_)
  );
  sg13g2_dfrbpq_1 _303_ (
    .CLK(clk),
    .D(_029_),
    .Q(\spidevice.spi_clk_buff[1][0] ),
    .RESET_B(_138_)
  );
  sg13g2_tiehi _304_ (
    .L_HI(_122_)
  );
  sg13g2_tiehi _305_ (
    .L_HI(_123_)
  );
  sg13g2_tiehi _306_ (
    .L_HI(_124_)
  );
  sg13g2_tiehi _307_ (
    .L_HI(_125_)
  );
  sg13g2_tiehi _308_ (
    .L_HI(_126_)
  );
  sg13g2_tiehi _309_ (
    .L_HI(_127_)
  );
  sg13g2_tiehi _310_ (
    .L_HI(_128_)
  );
  sg13g2_tiehi _311_ (
    .L_HI(_129_)
  );
  sg13g2_tiehi _312_ (
    .L_HI(_130_)
  );
  sg13g2_tiehi _313_ (
    .L_HI(_131_)
  );
  sg13g2_tiehi _314_ (
    .L_HI(_132_)
  );
  sg13g2_tiehi _315_ (
    .L_HI(_133_)
  );
  sg13g2_tiehi _316_ (
    .L_HI(_134_)
  );
  sg13g2_tiehi _317_ (
    .L_HI(_135_)
  );
  sg13g2_tiehi _318_ (
    .L_HI(_136_)
  );
  sg13g2_tiehi _319_ (
    .L_HI(_137_)
  );
  sg13g2_tiehi _320_ (
    .L_HI(_138_)
  );
  sg13g2_tiehi _321_ (
    .L_HI(_139_)
  );
  sg13g2_tiehi _322_ (
    .L_HI(_140_)
  );
  sg13g2_tiehi _323_ (
    .L_HI(_141_)
  );
  sg13g2_tiehi _324_ (
    .L_HI(_142_)
  );
  sg13g2_tiehi _325_ (
    .L_HI(_143_)
  );
  sg13g2_tiehi _326_ (
    .L_HI(_144_)
  );
  sg13g2_tiehi _327_ (
    .L_HI(_145_)
  );
  sg13g2_tiehi _328_ (
    .L_HI(_146_)
  );
  sg13g2_tiehi _329_ (
    .L_HI(_147_)
  );
  sg13g2_tiehi _330_ (
    .L_HI(_148_)
  );
  sg13g2_tiehi _331_ (
    .L_HI(_149_)
  );
  sg13g2_tiehi _332_ (
    .L_HI(_150_)
  );
  sg13g2_tiehi _333_ (
    .L_HI(_151_)
  );
  sg13g2_tielo _334_ (
    .L_LO(uio_oe[0])
  );
  sg13g2_tielo _335_ (
    .L_LO(uio_oe[1])
  );
  sg13g2_tielo _336_ (
    .L_LO(uio_oe[2])
  );
  sg13g2_tielo _337_ (
    .L_LO(uio_oe[3])
  );
  sg13g2_tielo _338_ (
    .L_LO(uio_oe[4])
  );
  sg13g2_tielo _339_ (
    .L_LO(uio_oe[5])
  );
  sg13g2_tielo _340_ (
    .L_LO(uio_oe[6])
  );
  sg13g2_tielo _341_ (
    .L_LO(uio_oe[7])
  );
  sg13g2_tielo _342_ (
    .L_LO(uio_out[0])
  );
  sg13g2_tielo _343_ (
    .L_LO(uio_out[1])
  );
  sg13g2_tielo _344_ (
    .L_LO(uio_out[2])
  );
  sg13g2_tielo _345_ (
    .L_LO(uio_out[3])
  );
  sg13g2_tielo _346_ (
    .L_LO(uio_out[4])
  );
  sg13g2_tielo _347_ (
    .L_LO(uio_out[5])
  );
  sg13g2_tielo _348_ (
    .L_LO(uio_out[6])
  );
  sg13g2_tielo _349_ (
    .L_LO(uio_out[7])
  );
  sg13g2_tielo _350_ (
    .L_LO(uo_out[3])
  );
  sg13g2_tielo _351_ (
    .L_LO(uo_out[4])
  );
  sg13g2_tielo _352_ (
    .L_LO(uo_out[5])
  );
  sg13g2_buf_1 _353_ (
    .A(\spidevice.spi_miso ),
    .X(uo_out[0])
  );
  sg13g2_buf_1 _354_ (
    .A(\spidevice.debug ),
    .X(uo_out[1])
  );
  sg13g2_buf_1 _355_ (
    .A(clk),
    .X(uo_out[2])
  );
  sg13g2_buf_1 _356_ (
    .A(\spidevice.led_status ),
    .X(uo_out[6])
  );
  sg13g2_buf_1 _357_ (
    .A(\spidevice.led_reset ),
    .X(uo_out[7])
  );
endmodule
